name: Broad Institute Ontology Reference
title: Broad Institute of MIT and Harvard Ontology Reference
markdown: kramdown
pygments: true
baseurl: /
imgurl: /images
author:
  name: Broad Institute Data Engineering

ontologies:

### NCI Thesaurus (NCIT) ###

  - id: ncithesaurus
    title: NCI Thesaurus
    description: >
      An ontology-like vocabulary that includes broad coverage of the cancer
      domain, including cancer related diseases, findings and abnormalities

    ontology_purl: https://stars.renci.org/var/NCIt/ncit.owl
    homepage: https://cabig.nci.nih.gov/concepts/EVS/

    products:
      - id: ncit.owl
        ontology_purl: https://stars.renci.org/var/NCIt/ncit.owl
      - id: ncit.obo
        ontology_purl: https://stars.renci.org/var/NCIt/ncit.obo

    contact:
      label: NCICB Support
      email: ncicb@pop.nci.nih.gov

    layout: ontology_detail

### Uber-anatomy ontology (UBERON) ###

  - id: uberon
    label: Uberon
    title: Uberon multi-species anatomy ontology
    description: >
      An integrated cross-species anatomy ontology covering animals and bridging
      multiple species-specific ontologies

    build:
      checkout: svn --ignore-externals co http://svn.code.sf.net/p/obo/svn/uberon/trunk
      email_cc: cjmungall@lbl.gov
      infallible: 1
      method: vcs
      system: svn
    dependencies:
      - id: go
        subset: uberon/go_import.owl
      - id: cl
        subset: uberon/cl_import.owl
      - id: chebi
        subset: uberon/chebi_import.owl
      - id: pr
        subset: uberon/pr_import.owl

    biosharing: https://www.biosharing.org/bsg-000016
    browsers:
      - label: RGD
        title: Gene Ontology AmiGO 2 Browser
        url: http://rgd.mcw.edu/rgdweb/ontology/view.html?acc_id=UBERON:0001062
      - label: AmiGO (SUBSET)
        title: Gene Ontology AmiGO 2 Browser
        url: http://amigo.geneontology.org/amigo/term/UBERON:0001062#display-lineage-tab

    canonical: uberon.owl
    contact:
      email: cjmungall@lbl.gov
      label: Chris Mungall

    depicted_by: http://uberon.github.io/images/u-logo.jpg

    domain: anatomy
    exampleClass: UBERON_0002046
    funded_by:
      - NIH R24OD011883
      - NIH R01HG004838
      - NIH P41HG002273
      - NSF DEB-0956049
    google_plus: +UberonOrg
    homepage: http://uberon.org

    layout: ontology_detail
    license:
      label: CC-BY
      logo: http://mirrors.creativecommons.org/presskit/buttons/80x15/png/by.png
      url: http://creativecommons.org/licenses/by/3.0/
    mailing_list: https://lists.sourceforge.net/lists/listinfo/obo-anatomy
    ontology_purl: http://purl.obolibrary.org/obo/uberon.owl
    page: http://en.wikipedia.org/wiki/Uberon
    products:
      - id: uberon.owl
        title: Uberon
        description: core ontology
        type: owl:Ontology
        is_canonical: true
        ontology_purl: http://purl.obolibrary.org/obo/uberon.owl

      - id: uberon/ext.owl
        title: Uberon extended
        description: >
          Uberon edition that includes subsets of other ontologies and axioms connecting
          to them
        type: owl:Ontology
        mireots_from: ncbitaxon
        ontology_purl: http://purl.obolibrary.org/obo/uberon/ext.owl

      - id: uberon/basic.obo
        title: Uberon basic
        description: Uberon edition that excludes external ontologies and most relations
        type: obo-basic-ontology
        format: obo
        ontology_purl: http://purl.obolibrary.org/obo/uberon/basic.obo

      - id: uberon/bridge/uberon-bridge-to-zfa.owl
        title: Uberon bridge to ZFA
        description: >
          Taxonomic equivalence axioms connecting zebrafish-specific classes
          to generic uberon counterparts
        type: BridgeOntology
        connects:
          - id: uberon
          - id: zfa
        ontology_purl: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-zfa.owl
        page: https://github.com/obophenotype/uberon/wiki/inter-anatomy-ontology-bridge-ontologies

      - id: uberon/bridge/uberon-bridge-to-ma.owl
        title: Uberon bridge to MA
        description: >
          Taxonomic equivalence axioms connecting adult mouse specific classes
          to generic uberon counterparts
        type: BridgeOntology
        connects:
          - id: uberon
          - id: ma
        ontology_purl: http://purl.obolibrary.org/obo/uberon/bridge/uberon-bridge-to-ma.owl
        page: https://github.com/obophenotype/uberon/wiki/inter-anatomy-ontology-bridge-ontologies

      - id: uberon/composite-metazoan.owl
        title: Uberon composite metazoan ontology
        description: Extended uberon plus all metazoan ontologies
        type: MergedOntology
        mireots_from: ehdaa2
        ontology_purl: http://purl.obolibrary.org/obo/uberon/composite-metazoan.owl
        page: https://github.com/obophenotype/uberon/wiki/Multi-species-composite-ontologies
        taxon: Metazoa

      - id: uberon/composite-vertebrate.owl
        title: Uberon composite vertebrate ontology
        type: MergedOntology
        mireots_from: ehdaa2
        ontology_purl: http://purl.obolibrary.org/obo/uberon/composite-vertebrate.owl
        page: https://github.com/obophenotype/uberon/wiki/Multi-species-composite-ontologies
        taxon: Metazoa

    publications:
      - id: http://www.ncbi.nlm.nih.gov/pubmed/22293552
        title: Uberon, an integrative multi-species anatomy ontology
      - id: http://www.ncbi.nlm.nih.gov/pubmed/25009735
        title: Unification of multi-species vertebrate anatomy ontologies for comparative biology in Uberon

    redirects:
      - match: releases/
        url: http://svn.code.sf.net/p/obo/svn/uberon/releases/
      - match: ""
        url: http://berkeleybop.org/ontologies/uberon/

    releases: http://purl.obolibrary.org/obo/uberon/releases/
    repository: https://github.com/obophenotype/uberon
    taxon:
      id: NCBITaxon:33208
      label: Metazoa

    tracker: https://github.com/obophenotype/uberon/issues
    twitter: uberanat
    type: owl:Ontology
    used_by:
      - label: bgee
        seeAlso: https://www.biosharing.org/biodbcore-000228
        type: Database
        url: http://bgee.org/

      - label: ENCODE
        seeAlso: https://www.biosharing.org/biodbcore-000034
        url: https://www.encodeproject.org/

      - label: FANTOM5
        url: http://fantom5-collaboration.gsc.riken.jp/

      - label: Monarch
        type: Database
        url: https://monarchinitiative.org/

      - label: GO Database
        type: Database
        url: https://geneontology.org/

      - label: Phenoscape
        url: http://phenoscape.org

      - label: Neuroscience Information Framework
        type: Database
        url: https://neuinfo.org/

      - label: SciCrunch
        type: Database
        url: https://scicrunch.org/

    wikidata_template: https://en.wikipedia.org/wiki/Template:Uberon

### CHEBI ###

  - id: chebi
    title: Chemical Entities of Biological Interest
    description: >
      A structured classification of molecular entities of biological interest
      focusing on 'small' chemical compounds.

    build:
      infallible: 1
      method: archive
      path: archive/main
      source_url: http://build.berkeleybop.org/job/build-chebi/lastSuccessfulBuild/artifact/*zip*/archive.zip

    browsers:
      - label: CHEBI
        title: EBI CHEBI Browser
        url: http://www.ebi.ac.uk/chebi/chebiOntology.do?treeView=true&chebiId=CHEBI:24431#graphView

    contact:
      email: gowen@ebi.ac.uk
      label: Gareth Owen

    domain: biochemistry
    homepage: http://www.ebi.ac.uk/chebi

    in_foundry_order: 1
    layout: ontology_detail
    ontology_purl: http://purl.obolibrary.org/obo/chebi.owl
    page: http://www.ebi.ac.uk/chebi/init.do?toolBarForward=userManual
    products:
      - id: chebi.owl
        ontology_purl: http://purl.obolibrary.org/obo/chebi.owl

      - id: chebi.obo
        ontology_purl: http://purl.obolibrary.org/obo/chebi.obo

    synonym_property:
      - http://www.geneontology.org/formats/oboInOwl#hasRelatedSynonym

    tracker: https://sourceforge.net/p/chebi/curator-requests/
    twitter: chebit
